name: CI
on:
  push:
    branches:
      - github
  pull_request:
    branches:
      - github

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:rawhide
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build fedpkg
        run: sudo dnf -y install fedpkg
      - name: Make SRPM
        run: |
          spectool -g mpibash.spec
          fedpkg srpm
      - name: Build rpm
        run: fedpkg local
